# Generated by Django 5.0.6 on 2024-10-28 04:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Powder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('powder_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('view', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('display_pic', models.ImageField(upload_to='display_pic')),
                ('another_pic', models.ImageField(upload_to='display_pic')),
                ('favorites', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='size_of_powder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='powder_review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('rating', models.CharField(choices=[('❤️', '❤️'), ('❤️🖤', '❤️🖤'), ('❤️🖤💚', '❤️🖤💚'), ('❤️🖤💚💙', '❤️🖤💚💙'), ('❤️🖤💚💙💜', '❤️🖤💚💙💜')], max_length=100)),
                ('Powder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='powder.powder')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='powder',
            name='size_of_powder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='powder.size_of_powder'),
        ),
    ]
