# Generated by Django 5.0.6 on 2024-10-29 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('powder', '0002_alter_powder_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='powder',
            name='size_of_powder',
        ),
        migrations.RemoveField(
            model_name='powder_review',
            name='Powder',
        ),
        migrations.RemoveField(
            model_name='powder_review',
            name='user',
        ),
        migrations.DeleteModel(
            name='size_of_powder',
        ),
        migrations.DeleteModel(
            name='Powder',
        ),
        migrations.DeleteModel(
            name='powder_review',
        ),
    ]
