# Generated by Django 5.0.6 on 2024-10-29 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shirt',
            name='shirt_brand',
        ),
        migrations.RemoveField(
            model_name='shirt',
            name='shirt_colour',
        ),
        migrations.RemoveField(
            model_name='shirt',
            name='shirt_price',
        ),
        migrations.RemoveField(
            model_name='shirt',
            name='type_of_shirt',
        ),
        migrations.RemoveField(
            model_name='review_shirt',
            name='shirt',
        ),
        migrations.DeleteModel(
            name='shirt_brand',
        ),
        migrations.DeleteModel(
            name='shirt_colour',
        ),
        migrations.DeleteModel(
            name='shirt_price',
        ),
        migrations.DeleteModel(
            name='shirt',
        ),
    ]
