# Generated by Django 5.0.6 on 2024-10-29 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0003_review_remove_review_geans_user_delete_type_of_shirt_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='range_geans_price',
            new_name='range_of_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='range_geans_price',
            new_name='range_of_price',
        ),
        migrations.AddField(
            model_name='product',
            name='Brand_shirt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_app.brand_shirt'),
        ),
        migrations.DeleteModel(
            name='review_shirt',
        ),
    ]
