# Generated by Django 5.0.6 on 2024-10-29 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0005_remove_range_of_price_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='Product',
        ),
        migrations.AddField(
            model_name='review',
            name='cetagory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_app.cetagory'),
        ),
    ]
