# Generated by Django 5.0.6 on 2024-10-29 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0007_remove_review_cetagory_review_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
        migrations.AddField(
            model_name='review',
            name='football_rating',
            field=models.CharField(blank=True, choices=[('⚽', '⚽'), ('⚽⚽', '⚽⚽'), ('⚽⚽⚽', '⚽⚽⚽'), ('⚽⚽⚽⚽', '⚽⚽⚽⚽'), ('⚽⚽⚽⚽⚽', '⚽⚽⚽⚽⚽')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='rating_geans',
            field=models.CharField(blank=True, choices=[('★', '★'), ('★★', '★★'), ('★★★', '★★★'), ('★★★★', '★★★★'), ('★★★★★', '★★★★★')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='rating_shirt',
            field=models.CharField(blank=True, choices=[('🧡', '🧡'), ('🧡💚', '🧡💚'), ('🧡💚🖤', '🧡💚🖤'), ('💙💚💛🧡', '💙💚💛🧡'), ('💙💚💛🧡💜', '💙💚💛🧡💜')], max_length=100, null=True),
        ),
    ]
