# Generated by Django 5.0.6 on 2024-10-29 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0009_rename_rating_shirt_review_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='abailable',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
