# Generated by Django 5.0.6 on 2024-10-31 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0017_football_cetagory_geans_cetagory_powder_cetagory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='type_of_geans',
        ),
        migrations.DeleteModel(
            name='type_of_geans',
        ),
    ]
