# Generated by Django 5.0.6 on 2024-10-31 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0018_remove_product_type_of_geans_delete_type_of_geans'),
    ]

    operations = [
        migrations.DeleteModel(
            name='view_model',
        ),
    ]
