# Generated by Django 5.0.6 on 2024-11-02 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0021_view_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ADD_TO_CART',
        ),
    ]
