# Generated by Django 5.0.6 on 2024-11-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0023_brand_saree_product_brand_saree'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type_your_product',
            field=models.CharField(blank=True, choices=[('Saree', 'Saree'), ('Geans', 'Geans'), ('Shirt', 'Shirt'), ('T shirt', 'T shirt'), ('Watch', 'Watch'), ('Powder', 'Powder'), ('Shoo', 'Shoo')], max_length=100, null=True),
        ),
    ]
