# Generated by Django 5.0.6 on 2024-11-07 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0024_product_type_your_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='eyes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
