# Generated by Django 5.0.6 on 2024-11-08 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0026_brand_geans_product_brand_geans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='back_image',
            field=models.ImageField(blank=True, null=True, upload_to='display_pic/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='display_image',
            field=models.ImageField(blank=True, null=True, upload_to='display_pic/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='font_image',
            field=models.ImageField(blank=True, null=True, upload_to='display_pic/'),
        ),
    ]
