# Generated by Django 5.0.6 on 2024-11-11 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0027_alter_product_back_image_alter_product_display_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['review_date']},
        ),
    ]
