# Generated by Django 5.0.6 on 2024-11-11 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0028_alter_review_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-review_date']},
        ),
    ]
