# Generated by Django 5.0.6 on 2024-11-15 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0031_brand_watch_cetagory_watch_dial_size_watch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Brand_Watch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_app.brand_watch'),
        ),
        migrations.AddField(
            model_name='product',
            name='Cetagory_watch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_app.cetagory_watch'),
        ),
        migrations.AddField(
            model_name='product',
            name='Dial_size_watch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_app.dial_size_watch'),
        ),
        migrations.AddField(
            model_name='product',
            name='Movement_Watch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_app.movement_watch'),
        ),
        migrations.AddField(
            model_name='product',
            name='Strap_metarail_watch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_app.strap_metarail_watch'),
        ),
        migrations.AddField(
            model_name='product',
            name='warenty_watch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_app.warenty_watch'),
        ),
    ]
