# Generated by Django 5.0.6 on 2024-11-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0032_product_brand_watch_product_cetagory_watch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FootBallWarentty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='type_your_product',
            field=models.CharField(blank=True, choices=[('Saree', 'Saree'), ('Geans', 'Geans'), ('Shirt', 'Shirt'), ('T shirt', 'T shirt'), ('Watch', 'Watch'), ('Powder', 'Powder'), ('Shoo', 'Shoo'), ('Football', 'Football')], max_length=100, null=True),
        ),
    ]
