# Generated by Django 5.0.6 on 2024-11-16 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0033_footballwarentty_alter_product_type_your_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(choices=[('Dhaka', 'Dhaka'), ('Chittagong', 'Chittagong'), ('Rajshahi', 'Rajshahi'), ('Khulna', 'Khulna'), ('Sylhet', 'Sylhet'), ('Barisal', 'Barisal'), ('Rangpur', 'Rangpur'), ('Mymensingh', 'Mymensingh'), ('Comilla', 'Comilla'), ('Bogura', 'Bogura'), ('Narayanganj', 'Narayanganj'), ('Narsingdi', 'Narsingdi'), ('Pabna', 'Pabna'), ('Jessore', 'Jessore'), ('Chandpur', 'Chandpur'), ('Tangail', 'Tangail'), ('Manikganj', 'Manikganj'), ('Kushtia', 'Kushtia'), ('Meherpur', 'Meherpur'), ('Satkhira', 'Satkhira'), ('Naogaon', 'Naogaon'), ('Khagrachari', 'Khagrachari'), ('Lalmonirhat', 'Lalmonirhat'), ('Dinajpur', 'Dinajpur'), ('Thakurgaon', 'Thakurgaon'), ('Moulvibazar', 'Moulvibazar'), ('Habiganj', 'Habiganj'), ('Sirajganj', 'Sirajganj'), ('Bogra', 'Bogra'), ('Netrakona', 'Netrakona'), ('Jhalokathi', 'Jhalokathi'), ('Chuadanga', 'Chuadanga'), ('Kishoreganj', 'Kishoreganj'), ('Shariatpur', 'Shariatpur'), ('Rajbari', 'Rajbari'), ('Magura', 'Magura'), ('Netrokona', 'Netrokona'), ("Cox's Bazar", "Cox's Bazar"), ('Madaripur', 'Madaripur'), ('Feni', 'Feni'), ('Moulvi Bazar', 'Moulvi Bazar'), ('Kurigram', 'Kurigram'), ('Brahmanbaria', 'Brahmanbaria'), ('Chattogram', 'Chattogram'), ('Meherpur', 'Meherpur'), ('Khulna', 'Khulna'), ('Noakhali', 'Noakhali'), ('Sundarbans', 'Sundarbans'), ('Jamuna', 'Jamuna'), ('Shibganj', 'Shibganj'), ('Sylhet Division', 'Sylhet Division'), ('Jamalpur', 'Jamalpur'), ('Rajshahi Division', 'Rajshahi Division'), ('Madhabkunda', 'Madhabkunda'), ('Bagerhat', 'Bagerhat')], max_length=300)),
                ('address', models.TextField()),
                ('contact_number', models.CharField(max_length=12)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
