# Generated by Django 5.0.6 on 2024-11-17 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0034_delivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='FootBallWarentty',
            new_name='SportsType',
        ),
        migrations.AddField(
            model_name='product',
            name='sports_Type',
            field=models.CharField(blank=True, choices=[('Football', 'Football'), ('Cricket Ball', 'Cricket Ball'), ('Tenis Ball', 'Tenis Ball'), ('Jursi', 'Jursi'), ('Boot', 'Boot'), ('Vascet Ball', 'Vascet Ball')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='team',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_app.team'),
        ),
        migrations.AddField(
            model_name='product',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_app.version'),
        ),
    ]
