# Generated by Django 5.0.6 on 2024-11-17 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0035_team_version_rename_footballwarentty_sportstype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type_your_product',
            field=models.CharField(blank=True, choices=[('Saree', 'Saree'), ('Geans', 'Geans'), ('Shirt', 'Shirt'), ('T shirt', 'T shirt'), ('Watch', 'Watch'), ('Powder', 'Powder'), ('Shoo', 'Shoo'), ('Sports', 'Sports')], max_length=100, null=True),
        ),
    ]
