# Generated by Django 5.0.6 on 2024-11-20 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0038_product_batsize_product_cricketbatbrand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sports_Type',
            field=models.CharField(blank=True, choices=[('Football', 'Football'), ('Cricket Ball', 'Cricket Ball'), ('Cricket Bat', 'Cricket Bat'), ('Jursi', 'Jursi'), ('Boot', 'Boot'), ('Basketball', 'Basketball'), ('Baseball', 'Baseball'), ('Tennis ball', 'Tennis ball'), ('Handball', 'Handball'), ('Rink Ball', 'Rink ball'), ('Volleyball ball', 'Volleyball ball')], max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
    ]
