# Generated by Django 5.0.6 on 2024-11-27 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0039_alter_product_sports_type_delete_delivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandOFJacket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOFJacket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WarrentyOFJacket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='type_your_product',
            field=models.CharField(blank=True, choices=[('Saree', 'Saree'), ('Geans', 'Geans'), ('Shirt', 'Shirt'), ('T shirt', 'T shirt'), ('Watch', 'Watch'), ('Powder', 'Powder'), ('Shoo', 'Shoo'), ('Sports', 'Sports'), ('Jacket', 'Jacket')], max_length=100, null=True),
        ),
    ]
