# Generated by Django 5.0.6 on 2024-11-27 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0041_size_of_geans_choice_size'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WarrentyOFJacket',
        ),
        migrations.AddField(
            model_name='product',
            name='BrandOFJacket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_app.brandofjacket'),
        ),
        migrations.AddField(
            model_name='warenty_watch',
            name='choice_type',
            field=models.CharField(blank=True, choices=[('jacket', 'jacket'), ('watch', 'watch')], max_length=1000, null=True),
        ),
    ]
