# Generated by Django 5.0.6 on 2024-11-27 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0043_mainmetariailsbat_choice_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand_geans',
            name='choice',
            field=models.CharField(blank=True, choices=[('Geans', 'Geans'), ('jacket', 'jacket')], max_length=100, null=True),
        ),
    ]
