# Generated by Django 5.0.6 on 2024-11-27 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0044_brand_geans_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='BrandOFJacket',
        ),
        migrations.AddField(
            model_name='product',
            name='TypeOFJacket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_app.typeofjacket'),
        ),
        migrations.DeleteModel(
            name='BrandOFJacket',
        ),
    ]
