# Generated by Django 5.0.6 on 2024-11-27 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0045_remove_product_brandofjacket_product_typeofjacket_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brand_geans',
            new_name='Brand',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Brand_geans',
            new_name='Brand',
        ),
    ]
