# Generated by Django 5.0.6 on 2024-11-27 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0046_rename_brand_geans_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='choice',
            field=models.CharField(blank=True, choices=[('geans', 'geans'), ('jacket', 'jacket')], max_length=100, null=True),
        ),
    ]
