# Generated by Django 5.0.6 on 2024-11-27 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0047_alter_brand_choice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='size_of_geans',
            new_name='size',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='size_of_geans',
            new_name='size',
        ),
    ]
