# Generated by Django 5.0.6 on 2024-11-28 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0048_rename_size_of_geans_size_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MainMetariailsBat',
            new_name='MainMetariails',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='MainMetariailsBat',
            new_name='MainMetariails',
        ),
    ]
