# Generated by Django 5.0.6 on 2024-12-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0049_rename_mainmetariailsbat_mainmetariails_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
