# Generated by Django 5.0.6 on 2024-12-11 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0051_alter_view_model_options_view_model_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='cetagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cetagorytype', models.CharField(blank=True, choices=[('Shirt', 'Shirt'), ('Saree', 'Saree'), ('Geans', 'Geans'), ('Football', 'Football'), ('Powder', 'Powder')], max_length=100, null=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='saree_cetagory',
        ),
        migrations.AlterModelOptions(
            name='view_model',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='product',
            name='football_cetagory',
        ),
        migrations.RemoveField(
            model_name='product',
            name='geans_cetagory',
        ),
        migrations.RemoveField(
            model_name='product',
            name='powder_cetagory',
        ),
        migrations.RemoveField(
            model_name='product',
            name='shirt_cetagory',
        ),
        migrations.AddField(
            model_name='product',
            name='cetagory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_app.cetagory'),
        ),
        migrations.DeleteModel(
            name='saree_cetagory',
        ),
    ]
