# Generated by Django 5.0.6 on 2024-12-11 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0052_cetagory_remove_product_saree_cetagory_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='football_cetagory',
        ),
        migrations.DeleteModel(
            name='geans_cetagory',
        ),
        migrations.DeleteModel(
            name='powder_cetagory',
        ),
        migrations.DeleteModel(
            name='shirt_cetagory',
        ),
    ]
