# Generated by Django 5.0.6 on 2024-12-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0053_delete_football_cetagory_delete_geans_cetagory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Brand_saree',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Brand_shirt',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Brand_Watch',
        ),
        migrations.RemoveField(
            model_name='product',
            name='CricketBatBrand',
        ),
        migrations.AlterField(
            model_name='brand',
            name='choice',
            field=models.CharField(blank=True, choices=[('geans', 'geans'), ('jacket', 'jacket'), ('Saree', 'Saree'), ('Shirt', 'Shirt'), ('Watch', 'Watch')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cetagory',
            name='cetagorytype',
            field=models.CharField(blank=True, choices=[('Shirt', 'Shirt'), ('Saree', 'Saree'), ('Geans', 'Geans'), ('Football', 'Football'), ('Powder', 'Powder'), ('Cricket Bat', 'Cricket Bat')], max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Brand_saree',
        ),
        migrations.DeleteModel(
            name='Brand_shirt',
        ),
        migrations.DeleteModel(
            name='Brand_Watch',
        ),
        migrations.DeleteModel(
            name='CricketBatBrand',
        ),
    ]
