# Generated by Django 5.0.6 on 2024-12-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0054_remove_product_brand_saree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='choice',
            field=models.CharField(blank=True, choices=[('geans', 'geans'), ('jacket', 'jacket'), ('Saree', 'Saree'), ('Shirt', 'Shirt'), ('Watch', 'Watch'), ('Cricket Bat', 'Cricket Bat')], max_length=100, null=True),
        ),
    ]
