# Generated by Django 5.0.6 on 2024-12-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0055_alter_brand_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='choice',
            field=models.CharField(blank=True, choices=[('geans', 'geans'), ('jacket', 'jacket'), ('Saree', 'Saree'), ('Shirt', 'Shirt'), ('Watch', 'Watch'), ('Cricket Bat', 'Cricket Bat'), ('Football', 'Football')], max_length=100, null=True),
        ),
    ]
