# Generated by Django 5.0.6 on 2024-12-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0056_alter_brand_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Cetagory_watch',
        ),
        migrations.AlterField(
            model_name='cetagory',
            name='cetagorytype',
            field=models.CharField(blank=True, choices=[('Shirt', 'Shirt'), ('Saree', 'Saree'), ('Geans', 'Geans'), ('Football', 'Football'), ('Powder', 'Powder'), ('Cricket Bat', 'Cricket Bat'), ('Watch', 'Watch')], max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Cetagory_watch',
        ),
    ]
