# Generated by Django 5.0.6 on 2024-12-16 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0057_remove_product_cetagory_watch_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cetagory',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='cetagory',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
