# Generated by Django 5.0.6 on 2024-12-16 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0058_alter_cetagory_options_cetagory_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cetagory',
            options={'ordering': ['date']},
        ),
    ]
