# Generated by Django 5.0.6 on 2024-12-16 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0059_alter_cetagory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cetagory',
            options={'ordering': ['-datetime_a']},
        ),
        migrations.RenameField(
            model_name='cetagory',
            old_name='date',
            new_name='datetime_a',
        ),
    ]
