# Generated by Django 5.0.6 on 2024-12-16 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0060_alter_cetagory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cetagory',
            options={'ordering': ['-name']},
        ),
    ]
