# Generated by Django 5.0.6 on 2024-12-18 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0062_remove_size_size_number_alter_size_choice_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='BatSize',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Dial_size_watch',
        ),
        migrations.DeleteModel(
            name='BatSize',
        ),
        migrations.DeleteModel(
            name='Dial_size_watch',
        ),
    ]
