# Generated by Django 5.0.6 on 2024-12-19 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0063_remove_product_batsize_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Strap_metarail_watch',
        ),
        migrations.AlterField(
            model_name='mainmetariails',
            name='choice_option',
            field=models.CharField(blank=True, choices=[('jacket', 'jacket'), ('Bat', 'Bat'), ('jursey', 'jursey'), ('geans', 'geans'), ('watch', 'watch')], max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Strap_metarail_watch',
        ),
    ]
