# Generated by Django 5.0.6 on 2024-12-20 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0064_remove_product_strap_metarail_watch_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['-country_name']},
        ),
    ]
