# Generated by Django 5.0.6 on 2024-12-20 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0065_alter_country_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['-name']},
        ),
        migrations.AlterModelOptions(
            name='colour',
            options={'ordering': ['-colour_name']},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['-name']},
        ),
    ]
