# Generated by Django 5.0.6 on 2024-12-23 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0066_alter_brand_options_alter_colour_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainmetariails',
            options={'ordering': ['-name']},
        ),
    ]
