# Generated by Django 5.0.6 on 2024-12-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0067_alter_mainmetariails_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainmetariails',
            name='choice_option',
            field=models.CharField(blank=True, choices=[('jacket', 'jacket'), ('Bat', 'Bat'), ('jursey', 'jursey'), ('geans', 'geans'), ('watch', 'watch'), ('Saree', 'Saree'), ('Football', 'Football')], max_length=100, null=True),
        ),
    ]
