# Generated by Django 5.0.6 on 2024-10-29 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ball',
            name='ball_colour',
        ),
        migrations.RemoveField(
            model_name='review_football',
            name='Ball',
        ),
        migrations.RemoveField(
            model_name='review_football',
            name='user',
        ),
        migrations.DeleteModel(
            name='ball_colour',
        ),
        migrations.DeleteModel(
            name='Ball',
        ),
        migrations.DeleteModel(
            name='review_football',
        ),
    ]
