# Generated by Django 5.0.6 on 2024-10-28 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('man', '0009_size_of_geans_remove_geans_size_geans_size_of_geans'),
        ('woman_app', '0003_type_of_sadi_type_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='geans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='man.geans'),
        ),
    ]
