# Generated by Django 5.0.6 on 2024-10-28 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('woman_app', '0004_review_geans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='geans',
        ),
    ]
