# Generated by Django 5.0.6 on 2024-10-28 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('woman_app', '0005_remove_review_geans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='name',
        ),
    ]
