# Generated by Django 5.0.6 on 2024-10-28 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woman_app', '0007_alter_sadi_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='range_price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='sadi',
            name='price',
        ),
        migrations.AddField(
            model_name='sadi',
            name='fixed_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sadi',
            name='range_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='woman_app.range_price'),
        ),
        migrations.DeleteModel(
            name='price',
        ),
    ]
