# Generated by Django 5.0.6 on 2024-10-28 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woman_app', '0009_cetagory_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='sadi',
        ),
        migrations.AddField(
            model_name='review',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='woman_app.product'),
        ),
    ]
