# Generated by Django 5.0.6 on 2024-10-29 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('woman_app', '0010_remove_review_sadi_review_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Cetagory',
        ),
        migrations.RemoveField(
            model_name='sadi',
            name='colour',
        ),
        migrations.RemoveField(
            model_name='product',
            name='colour',
        ),
        migrations.RemoveField(
            model_name='product',
            name='country',
        ),
        migrations.RemoveField(
            model_name='sadi',
            name='country',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Type_Of',
        ),
        migrations.RemoveField(
            model_name='product',
            name='range_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
        migrations.RemoveField(
            model_name='sadi',
            name='range_price',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sadi',
            name='Type_Of',
        ),
        migrations.RemoveField(
            model_name='sadi',
            name='size',
        ),
        migrations.DeleteModel(
            name='Cetagory',
        ),
        migrations.DeleteModel(
            name='colour',
        ),
        migrations.DeleteModel(
            name='country',
        ),
        migrations.DeleteModel(
            name='product',
        ),
        migrations.DeleteModel(
            name='range_price',
        ),
        migrations.DeleteModel(
            name='review',
        ),
        migrations.DeleteModel(
            name='Type_Of',
        ),
        migrations.DeleteModel(
            name='sadi',
        ),
        migrations.DeleteModel(
            name='size',
        ),
    ]
