# Generated by Django 5.0.6 on 2024-10-30 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('woman_app', '0011_remove_product_cetagory_remove_sadi_colour_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Marketing_Executive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='woman_app.location')),
            ],
        ),
    ]
