# Generated by Django 5.0.6 on 2024-10-30 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woman_app', '0012_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketing_executive',
            name='Location',
        ),
        migrations.AddField(
            model_name='marketing_executive',
            name='Location',
            field=models.ManyToManyField(blank=True, null=True, to='woman_app.location'),
        ),
    ]
