# Generated by Django 5.0.6 on 2024-10-30 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woman_app', '0013_remove_marketing_executive_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketing_executive',
            name='Location',
        ),
        migrations.AddField(
            model_name='marketing_executive',
            name='Location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='woman_app.location'),
        ),
    ]
