# Generated by Django 5.0.6 on 2024-10-30 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('woman_app', '0014_remove_marketing_executive_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketing_executive',
            name='Location',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Marketing_Executive',
        ),
    ]
