# Generated by Django 5.1.2 on 2024-10-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('man', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geans',
            name='geans_size',
        ),
        migrations.AddField(
            model_name='geans',
            name='geans_size',
            field=models.ManyToManyField(to='man.geans_size'),
        ),
    ]
