# Generated by Django 5.1.2 on 2024-10-27 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('man', '0002_remove_geans_geans_size_geans_geans_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geans',
            name='geans_size',
        ),
        migrations.AddField(
            model_name='geans',
            name='geans_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='man.geans_size'),
        ),
    ]
