# Generated by Django 5.1.2 on 2024-10-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('man', '0004_geans_price_geans_geans_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='geans',
            name='back_image',
            field=models.ImageField(blank=True, null=True, upload_to='display_pic'),
        ),
        migrations.AddField(
            model_name='geans',
            name='display_image',
            field=models.ImageField(blank=True, null=True, upload_to='display_pic'),
        ),
        migrations.AddField(
            model_name='geans',
            name='font_image',
            field=models.ImageField(blank=True, null=True, upload_to='display_pic'),
        ),
    ]
