# Generated by Django 5.1.2 on 2024-10-27 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('man', '0006_brand_remove_geans_geans_size_geans_colour_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='colour_of_geans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='geans',
            name='colour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='man.colour_of_geans'),
        ),
    ]
