# Generated by Django 5.1.2 on 2024-10-27 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('man', '0008_geans_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='size_of_geans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_number', models.IntegerField(blank=True, default=34, null=True)),
                ('size_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='geans',
            name='size',
        ),
        migrations.AddField(
            model_name='geans',
            name='size_of_geans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='man.size_of_geans'),
        ),
    ]
