# Generated by Django 5.0.6 on 2024-10-28 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('man', '0010_review_geans'),
    ]

    operations = [
        migrations.CreateModel(
            name='type_of_geans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='geans',
            name='type_of_geans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='man.type_of_geans'),
        ),
    ]
