# Generated by Django 5.0.6 on 2024-10-28 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('man', '0011_type_of_geans_geans_type_of_geans'),
    ]

    operations = [
        migrations.AddField(
            model_name='geans',
            name='view',
            field=models.BooleanField(default=False),
        ),
    ]
