# Generated by Django 5.0.6 on 2024-10-28 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('man', '0016_shirt_favorites_shirt_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review_geans',
            name='geans',
        ),
        migrations.RemoveField(
            model_name='review_geans',
            name='name',
        ),
        migrations.AddField(
            model_name='review_geans',
            name='shirt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='man.shirt'),
        ),
        migrations.AlterField(
            model_name='review_geans',
            name='rating',
            field=models.CharField(choices=[('🧡', '🧡'), ('🧡💚', '🧡💚'), ('🧡💚🖤', '🧡💚🖤'), ('💙💚💛🧡', '💙💚💛🧡'), ('💙💚💛🧡💜', '💙💚💛🧡💜')], max_length=100),
        ),
    ]
