# Generated by Django 5.0.6 on 2024-10-28 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('man', '0017_remove_review_geans_geans_remove_review_geans_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review_geans',
            name='shirt',
        ),
        migrations.AddField(
            model_name='review_geans',
            name='geans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='man.geans'),
        ),
        migrations.AlterField(
            model_name='review_geans',
            name='rating',
            field=models.CharField(choices=[('★', '★'), ('★★', '★★'), ('★★★', '★★★'), ('★★★★', '★★★★'), ('★★★★★', '★★★★★')], max_length=100),
        ),
        migrations.CreateModel(
            name='review_shirt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('rating', models.CharField(choices=[('🧡', '🧡'), ('🧡💚', '🧡💚'), ('🧡💚🖤', '🧡💚🖤'), ('💙💚💛🧡', '💙💚💛🧡'), ('💙💚💛🧡💜', '💙💚💛🧡💜')], max_length=100)),
                ('shirt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='man.shirt')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
