# Generated by Django 5.0.6 on 2024-10-29 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('man', '0019_add_to_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geans',
            name='Brand',
        ),
        migrations.RemoveField(
            model_name='geans',
            name='colour',
        ),
        migrations.RemoveField(
            model_name='geans',
            name='range_geans_price',
        ),
        migrations.RemoveField(
            model_name='geans',
            name='size_of_geans',
        ),
        migrations.RemoveField(
            model_name='geans',
            name='type_of_geans',
        ),
        migrations.RemoveField(
            model_name='review_geans',
            name='geans',
        ),
        migrations.RemoveField(
            model_name='review_geans',
            name='user',
        ),
        migrations.RemoveField(
            model_name='review_shirt',
            name='shirt',
        ),
        migrations.RemoveField(
            model_name='review_shirt',
            name='user',
        ),
        migrations.RemoveField(
            model_name='shirt',
            name='shirt_brand',
        ),
        migrations.RemoveField(
            model_name='shirt',
            name='shirt_colour',
        ),
        migrations.RemoveField(
            model_name='shirt',
            name='shirt_price',
        ),
        migrations.RemoveField(
            model_name='shirt',
            name='type_of_shirt',
        ),
        migrations.DeleteModel(
            name='ADD_TO_CART',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='colour_of_geans',
        ),
        migrations.DeleteModel(
            name='range_geans_price',
        ),
        migrations.DeleteModel(
            name='size_of_geans',
        ),
        migrations.DeleteModel(
            name='type_of_geans',
        ),
        migrations.DeleteModel(
            name='geans',
        ),
        migrations.DeleteModel(
            name='review_geans',
        ),
        migrations.DeleteModel(
            name='review_shirt',
        ),
        migrations.DeleteModel(
            name='shirt_brand',
        ),
        migrations.DeleteModel(
            name='shirt_colour',
        ),
        migrations.DeleteModel(
            name='shirt_price',
        ),
        migrations.DeleteModel(
            name='shirt',
        ),
        migrations.DeleteModel(
            name='type_of_shirt',
        ),
    ]
