# Generated by Django 5.0.6 on 2024-11-02 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_to_cart', '0004_alter_add_to_cart_total_price'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='add_to_cart',
            unique_together=set(),
        ),
    ]
