# Generated by Django 5.0.6 on 2024-11-04 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_to_cart', '0007_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='user',
        ),
    ]
