# Generated by Django 5.0.6 on 2024-11-10 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_to_cart', '0008_remove_cartitems_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='orderded',
        ),
    ]
