# Generated by Django 5.0.6 on 2024-11-10 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_to_cart', '0009_remove_cart_orderded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='price',
        ),
    ]
