# Generated by Django 5.0.6 on 2024-11-13 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_to_cart', '0010_remove_cartitems_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
