# Generated by Django 5.0.6 on 2024-11-21 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_to_cart', '0012_alter_cartitems_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='orderded',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yourPhone', models.CharField(max_length=12)),
                ('zila', models.CharField(choices=[('Dhaka', 'Dhaka'), ('Chittagong', 'Chittagong'), ('Khulna', 'Khulna'), ('Rajshahi', 'Rajshahi'), ('Barisal', 'Barisal'), ('Sylhet', 'Sylhet'), ('Rangpur', 'Rangpur'), ('Mymensingh', 'Mymensingh'), ('Narsingdi', 'Narsingdi'), ('Tangail', 'Tangail'), ('Comilla', 'Comilla'), ('Pabna', 'Pabna'), ('Bogra', 'Bogra'), ('Jessore', 'Jessore'), ('Cox’s Bazar', 'Cox’s Bazar'), ('Narayanganj', 'Narayanganj'), ('Feni', 'Feni'), ('Khagrachari', 'Khagrachari'), ('Manikganj', 'Manikganj'), ('Madaripur', 'Madaripur'), ('Gazipur', 'Gazipur'), ('Moulvibazar', 'Moulvibazar'), ('Chuadanga', 'Chuadanga'), ('Shariatpur', 'Shariatpur'), ('Netrokona', 'Netrokona'), ('Habiganj', 'Habiganj'), ('Lalmonirhat', 'Lalmonirhat'), ('Dinajpur', 'Dinajpur'), ('Patuakhali', 'Patuakhali'), ('Meherpur', 'Meherpur'), ('Mongla', 'Mongla'), ('Jhalokathi', 'Jhalokathi'), ('Pirojpur', 'Pirojpur'), ('Khulna', 'Khulna'), ('Satkhira', 'Satkhira'), ('Chandpur', 'Chandpur'), ('Jamuna', 'Jamuna'), ('Shibganj', 'Shibganj'), ('Sherpur', 'Sherpur'), ('Netrakona', 'Netrakona'), ('Nilphamari', 'Nilphamari'), ('Rangamati', 'Rangamati'), ('Kishoreganj', 'Kishoreganj'), ('Sherpur', 'Sherpur'), ('Tangail', 'Tangail'), ('Moulvibazar', 'Moulvibazar'), ('Brahmanbaria', 'Brahmanbaria'), ('Kurigram', 'Kurigram'), ('Thakurgaon', 'Thakurgaon'), ('Rangpur', 'Rangpur'), ('Chattogram', 'Chattogram'), ('Sherpur', 'Sherpur'), ('Natore', 'Natore'), ('Pabna', 'Pabna'), ('Narsingdi', 'Narsingdi'), ('Jhalokathi', 'Jhalokathi'), ('Manikganj', 'Manikganj'), ('Satkhira', 'Satkhira'), ('Chittagong', 'Chittagong'), ('Brahmanbaria', 'Brahmanbaria')], max_length=1000)),
                ('country', models.CharField(choices=[('Afghanistan', 'Afghanistan'), ('Albania', 'Albania'), ('Algeria', 'Algeria'), ('Andorra', 'Andorra'), ('Angola', 'Angola'), ('Antigua and Barbuda', 'Antigua and Barbuda'), ('Argentina', 'Argentina'), ('Armenia', 'Armenia'), ('Australia', 'Australia'), ('Austria', 'Austria'), ('Azerbaijan', 'Azerbaijan'), ('Bahamas', 'Bahamas'), ('Bahrain', 'Bahrain'), ('Bangladesh', 'Bangladesh'), ('Barbados', 'Barbados'), ('Belarus', 'Belarus'), ('Belgium', 'Belgium'), ('Belize', 'Belize'), ('Benin', 'Benin'), ('Bhutan', 'Bhutan'), ('Bolivia', 'Bolivia'), ('Bosnia and Herzegovina', 'Bosnia and Herzegovina'), ('Botswana', 'Botswana'), ('Brazil', 'Brazil'), ('Brunei', 'Brunei'), ('Bulgaria', 'Bulgaria'), ('Burkina Faso', 'Burkina Faso'), ('Burundi', 'Burundi'), ('Cabo Verde', 'Cabo Verde'), ('Cambodia', 'Cambodia'), ('Cameroon', 'Cameroon'), ('Canada', 'Canada'), ('Central African Republic', 'Central African Republic'), ('Chad', 'Chad'), ('Chile', 'Chile'), ('China', 'China'), ('Colombia', 'Colombia'), ('Comoros', 'Comoros'), ('Congo (Congo-Brazzaville)', 'Congo (Congo-Brazzaville)'), ('Costa Rica', 'Costa Rica'), ('Croatia', 'Croatia'), ('Cuba', 'Cuba'), ('Cyprus', 'Cyprus'), ('Czech Republic', 'Czech Republic'), ('Democratic Republic of the Congo', 'Democratic Republic of the Congo'), ('Denmark', 'Denmark'), ('Djibouti', 'Djibouti'), ('Dominica', 'Dominica'), ('Dominican Republic', 'Dominican Republic'), ('Ecuador', 'Ecuador'), ('Egypt', 'Egypt'), ('El Salvador', 'El Salvador'), ('Equatorial Guinea', 'Equatorial Guinea'), ('Eritrea', 'Eritrea'), ('Estonia', 'Estonia'), ('Eswatini', 'Eswatini'), ('Ethiopia', 'Ethiopia'), ('Fiji', 'Fiji'), ('Finland', 'Finland'), ('France', 'France'), ('Gabon', 'Gabon'), ('Gambia', 'Gambia'), ('Georgia', 'Georgia'), ('Germany', 'Germany'), ('Ghana', 'Ghana')], max_length=1000)),
                ('Divison', models.CharField(choices=[('Dhaka', 'Dhaka'), ('Chittagong', 'Chittagong'), ('Khulna', 'Khulna'), ('Rajshahi', 'Rajshahi'), ('Barisal', 'Barisal'), ('Sylhet', 'Sylhet'), ('Rangpur', 'Rangpur'), ('Mymensingh', 'Mymensingh')], max_length=1000)),
                ('upzlia', models.CharField(choices=[('Agailjhara', 'Agailjhara'), ('Aklia', 'Aklia'), ('Alamdanga', 'Alamdanga'), ('Bagatipara', 'Bagatipara'), ('Bagerhat Sadar', 'Bagerhat Sadar'), ('Bakerganj', 'Bakerganj'), ('Baliakandi', 'Baliakandi'), ('Banaripara', 'Banaripara'), ('Barisal Sadar', 'Barisal Sadar'), ('Bhola Sadar', 'Bhola Sadar'), ('Chandanaish', 'Chandanaish'), ('Companygonj', 'Companygonj'), ('Chhagalnaiya', 'Chhagalnaiya'), ('Chilmari', 'Chilmari'), ('Chondonaish', 'Chondonaish'), ('Comilla Sadar', 'Comilla Sadar'), ('Daulatkhan', 'Daulatkhan'), ('Dohar', 'Dohar'), ('Feni Sadar', 'Feni Sadar'), ('Gopalganj Sadar', 'Gopalganj Sadar'), ('Habiganj Sadar', 'Habiganj Sadar'), ('Jamalganj', 'Jamalganj'), ('Jhalokathi Sadar', 'Jhalokathi Sadar'), ('Jhenaidah Sadar', 'Jhenaidah Sadar'), ('Kagojdia', 'Kagojdia'), ('Kaliganj', 'Kaliganj'), ('Khulna Sadar', 'Khulna Sadar'), ('Kusumgram', 'Kusumgram'), ('Lalmonirhat', 'Lalmonirhat'), ('Madaripur', 'Madaripur'), ('Magura Sadar', 'Magura Sadar'), ('Manikganj', 'Manikganj'), ('Moulvibazar Sadar', 'Moulvibazar Sadar'), ('Munshiganj Sadar', 'Munshiganj Sadar'), ('Mymensingh', 'Mymensingh'), ('Naogaon Sadar', 'Naogaon Sadar'), ('Narayanganj', 'Narayanganj'), ('Narsingdi', 'Narsingdi'), ('Netrakona', 'Netrakona'), ('Nilphamari', 'Nilphamari'), ('Pabna', 'Pabna'), ('Panchagarh', 'Panchagarh'), ('Patuakhali', 'Patuakhali'), ('Pirojpur', 'Pirojpur'), ('Rajshahi', 'Rajshahi'), ('Rangamati', 'Rangamati'), ('Rangpur Sadar', 'Rangpur Sadar'), ('Satkhira Sadar', 'Satkhira Sadar'), ('Shariatpur', 'Shariatpur'), ('Sherpur', 'Sherpur'), ('Sreemangal', 'Sreemangal'), ('Sylhet Sadar', 'Sylhet Sadar'), ('Tangail', 'Tangail'), ('Thakurgaon', 'Thakurgaon'), ('Upojilla', 'Upojilla')], max_length=1000)),
                ('deliverystatus', models.CharField(choices=[('Pendding', 'Pendding'), ('Accepted', 'Accepted')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
