# Generated by Django 5.0.6 on 2024-11-21 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_to_cart', '0013_cart_orderded_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='Divison',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='country',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='upzlia',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='zila',
            field=models.CharField(max_length=1000),
        ),
    ]
