# Generated by Django 5.0.6 on 2024-11-21 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_to_cart', '0014_alter_delivery_divison_alter_delivery_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='country',
        ),
    ]
