# Generated by Django 5.0.6 on 2024-11-22 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_to_cart', '0015_remove_delivery_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='add_to_cart.cart'),
        ),
    ]
