# Generated by Django 5.0.6 on 2024-11-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_to_cart', '0016_delivery_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
