# Generated by Django 5.0.6 on 2024-11-25 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_to_cart', '0017_delivery_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitems',
            name='product',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='user',
        ),
        migrations.DeleteModel(
            name='cart',
        ),
        migrations.DeleteModel(
            name='CartItems',
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
    ]
