# Generated by Django 5.0.6 on 2024-12-04 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_to_cart', '0029_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='upzila',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='zila',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
