# Generated by Django 5.0.6 on 2024-12-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_to_cart', '0033_remove_order_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='oderdate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
